// <auto-generated />
using System;
using ContentSvc.WebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContentSvc.WebApi.Migrations
{
    [DbContext(typeof(ContentSvcContext))]
    partial class ContentSvcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ContentSvc.Model.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnName("expired_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Key")
                        .HasColumnName("key")
                        .HasColumnType("varchar(28) CHARACTER SET utf8mb4")
                        .HasMaxLength(28);

                    b.Property<string>("MinioUserId")
                        .IsRequired()
                        .HasColumnName("minio_user_id")
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.Property<string>("Remarks")
                        .HasColumnName("remarks")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<int>("Role")
                        .HasColumnName("role")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_api_keys");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasName("ix_api_keys_key");

                    b.HasIndex("MinioUserId")
                        .HasName("ix_api_keys_minio_user_id");

                    b.ToTable("api_keys");
                });

            modelBuilder.Entity("ContentSvc.Model.Entities.MinioUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("access_key")
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.Property<string>("SecretKey")
                        .HasColumnName("secret_key")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ServiceId")
                        .HasColumnName("service_id")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_minio_users");

                    b.HasIndex("ServiceId")
                        .HasName("ix_minio_users_service_id");

                    b.ToTable("minio_users");
                });

            modelBuilder.Entity("ContentSvc.Model.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatorId")
                        .HasColumnName("creator_id")
                        .HasColumnType("int");

                    b.Property<Guid>("DeletedFlag")
                        .HasColumnName("deleted_flag")
                        .HasColumnType("char(36)");

                    b.Property<string>("Desc")
                        .HasColumnName("desc")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(16) CHARACTER SET utf8mb4")
                        .HasMaxLength(16);

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.ToTable("services");
                });

            modelBuilder.Entity("ContentSvc.Model.Entities.ApiKey", b =>
                {
                    b.HasOne("ContentSvc.Model.Entities.MinioUser", "MinioUser")
                        .WithMany("ApiKeys")
                        .HasForeignKey("MinioUserId")
                        .HasConstraintName("fk_api_keys_minio_users_minio_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentSvc.Model.Entities.MinioUser", b =>
                {
                    b.HasOne("ContentSvc.Model.Entities.Service", "Service")
                        .WithMany("MinioUsers")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("fk_minio_users_services_service_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
